#!/usr/bin/env php
<?php

/* use composer generated autoloader */
require_once('vendor/autoload.php');

use XmlSplitter\XmlSplitterApplication;
use XmlSplitter\Command\SplitCommand;

$app = new XmlSplitterApplication();
$app->run();
